### ISSUE TITLE
如何在谷歌浏览器使用？

### ISSUE THREAD

**Issue by b1fly** [s7safe/Easy-XSS-V2#1]
如何在谷歌浏览器安装？

**Comment by LztCode** [comment]
我修改了，支持谷歌浏览器
https://github.com/LztCode/XssBar

**Comment by LztCode** [comment]
我修改了，支持谷歌浏览器
https://github.com/LztCode/XssBar

**Comment by s7safe** [comment]
近期我会把这个项目重做，我在GitHub发现了一些右键能够一键监测漏洞的一些插件，到时候集中到一个插件里，咱们一起使用，可以先用上面那个兄弟的谷歌版本， 我重点写火狐的插件。

**Comment by lishixin7777** [comment]
别忘了搞呀怎么还不出

**Comment by lishixin7777** [comment]
> 近期我会把这个项目重做，我在GitHub发现了一些右键能够一键监测漏洞的一些插件，到时候集中到一个插件里，咱们一起使用，可以先用上面那个兄弟的谷歌版本， 我重点写火狐的插件。

重做的项目呢，2025了已经

**Comment by s7safe** [comment]
雏形就是那个https://github.com/s7safe/XSSVB 现在有dome 到时候 结合成插件到火狐里面，我工作有点太忙了，所以进度缓慢

**Comment by lishixin7777** [comment]
haha,雀氏够忙的
